name: build

on: [push, pull_request]

jobs:
  build-with-pip:
    name: ${{ matrix.os }}/py${{ matrix.python-version }}/pip
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    env:
      MPLBACKEND: agg
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display versions
        run: python -V; pip -V
      - name: Install dependencies and package
        shell: bash
        run: pip install -U -e .'[tests]'
      - name: Run docstring tests
        run: pytest --doctest-modules --ignore=pyxem/tests pyxem
      - name: Run tests
        run: pytest --cov=pyxem --runslow --pyargs pyxem
      - name: Generate line coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: coverage report --show-missing
      - name: Upload coverage to Coveralls
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true

  coveralls-finish:
    needs: build-with-pip
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true

  build_doc:
    name: Build doc
    runs-on: ubuntu-latest
    env:
      BUILD_DEPS: python3-dev build-essential graphviz
      LATEX_DEPS: dvipng latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    steps:
      - uses: actions/checkout@v2

      - uses: ericpre/sphinx-action@latest_sphinx
        with:

          pre-build-command: "apt-get update -y && apt-get install -y ${{ env.BUILD_DEPS }} ${{ env.LATEX_DEPS }}  && pip install -e .[all,doc]"
          build-command: make html
          docs-folder: doc/

      - uses: actions/upload-artifact@v2
        with:
          path: ./doc/_build/html/
          name: doc_build