name: Documentation

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'pre-commit-ci-update-config'
  workflow_dispatch:

jobs:
  Build:
    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/doc.yml@main
    with:
      # install with speed extra to avoid warnings
      pip_extra_doc: 'all,doc'
      # graphviz is required to build mermaid graph
      # optipng is required to optimize thumbnail
      install_package_ubuntu: graphviz optipng
      check_links: true
      doctest: false
      # "-W --keep-going" should be used but there are currently too many failures
      #SPHINXOPTS: '-W --keep-going --jobs 4'
      SPHINXOPTS: '--jobs 4'
      ORGANISATION: 'pyxem'
      CACHE_GALLERY_EXAMPLES: './doc/examples'
      CACHE_POOCH: 'pyxem'

  Push_on_tag:
    needs: Build
    # Push only on tag and update the "current" documentation
    if: ${{ github.repository_owner == 'pyxem' && startsWith(github.ref, 'refs/tags/') }}
    permissions:
      # needs write permission to push the docs to gh-pages
      contents: write
    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/push_doc.yml@main
