name: Documentation

on:
  pull_request_target:
    types: [opened, reopened, synchronize, closed]
  push:
    branches: [ main ]
    tags: [ "v*" ]   # deploy versioned docs on tags like v1.2.0
  workflow_dispatch:

jobs:
  Build:
    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/doc.yml@main
    with:
      # install with speed extra to avoid warnings
      pip_extra_doc: 'all,doc'
      # graphviz is required to build mermaid graph
      # optipng is required to optimize thumbnail
      install_package_ubuntu: graphviz optipng
      check_links: true
      doctest: false
      # "-W --keep-going" should be used but there are currently too many failures
      #SPHINXOPTS: '-W --keep-going --jobs 4'
      SPHINXOPTS: '--jobs 4'
      ORGANISATION: 'pyxem'
      CACHE_GALLERY_EXAMPLES: './doc/examples'
      CACHE_POOCH: 'pyxem'

  Deploy_dev_docs:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      # Deploy docs for main branch -> /dev/
      - name: Deploy dev docs
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./doc/_build/html/
          destination_dir: dev
          force_orphan: false   # keep history for versioned docs

      # Build redirect page for latest version
      - name: Build index redirect
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch')
        run: |
          VERSION=${GITHUB_REF_NAME}   # e.g. v1.2.0
          mkdir -p redirect
          cat <<EOF > redirect/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=${VERSION}/">
              <script>window.location.href='${VERSION}/';</script>
            </head>
            <body>
              <p>Redirecting to <a href="${VERSION}/">latest documentation</a>...</p>
            </body>
          </html>
          EOF

      # Deploy versioned docs -> /vX.Y.Z/
      - name: Deploy versioned docs
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./doc/_build/html/
          destination_dir: ${{ github.ref_name }}   # e.g. v1.2.0
          force_orphan: false

      # Update root redirect to latest version
      - name: Update root redirect
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: redirect
          destination_dir: .   # root of gh-pages
          keep_files: true     # don’t remove previous docs
          force_orphan: false

      # Deploy PR preview (staging repo)
      - name: Deploy PR preview
        if: github.event_name == 'pull_request_target'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./doc/_build/html/
          deploy-repository: CSSFrancis/pyxem-docs-staging
          token: ${{ secrets.PREVIEW_DEPLOY_KEY }}
          comment: true   # sticky PR comment with preview link