name: Docs PR Preview # STOP: Any changes here should be carefully reviewed before merging
# See https://github.com/pyxem/pyxem/issues/1150 for context on this PR setup
on:
  pull_request_target: # use pull_request_target to have access to secrets for forks. Will run on the base branch
    types: [opened, reopened, synchronize, closed] # On closed we will remove the preview

jobs:
  build:
    uses: ./.github/workflows/docs-build.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@9f77b1d057b494e662c50b8ca40ecc63f21e0887 # uses a full len SHA per https://docs.github.com/en/actions/how-tos/write-workflows/choose-and-customize-actions#using-shas
        with:
          source-dir: ./doc/_build/html/
          deploy-repository: CSSFrancis/pyxem-docs-staging
          token: ${{ secrets.PREVIEW_DEPLOY_KEY }} # PAT with permissions to edit Content in CSSFrancis/pyxem-docs-staging
          comment: true # Add a comment to the PR with the preview link