name: Docs Dev Deploy

on:
  push:
    branches: [ main ]
    if: github.repository == 'pyxem/pyxem'
jobs:
  build:
    uses: ./.github/workflows/docs-build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built docs
        uses: actions/download-artifact@v4
        with:
          name: doc_html
          path: ./doc/_build/html
      - name: Deploy dev docs
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # uses a full len SHA per https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/find-and-customize-actions#using-shas
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir:  doc/_build/html
          destination_dir: dev
          force_orphan: false