name: Docs Release Deploy

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (for manual run)'
        required: false # for manual runs, set the tag version to deploy

jobs:
  build:
    uses: ./.github/workflows/docs-build.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build index redirect
        run: |
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          mkdir -p redirect
          cat <<EOF > redirect/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=${VERSION}/">
              <script>window.location.href='${VERSION}/';</script>
            </head>
            <body>
              <p>Redirecting to <a href="${VERSION}/">latest documentation</a>...</p>
            </body>
          </html>
          EOF

      - name: Deploy versioned docs
        uses: peaceiris/actions-gh-pages@4b09552702d0b65573696410d4707c765da2630b # uses a full len SHA per https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/find-and-customize-actions#using-shas
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./doc/_build/html/
          destination_dir: ${{ github.event.inputs.version || github.ref_name }} # deploy to a folder matching the tag version
          force_orphan: false

      - name: Update root redirect
        uses:  peaceiris/actions-gh-pages@4b09552702d0b65573696410d4707c765da2630b # uses a full len SHA per https://docs.github.com/en/actions/how-tos/write-workflows/choose-and-customize-actions#using-shas
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: redirect # update the root redirect
          destination_dir: .
          keep_files: true
          force_orphan: false